[mypy]
python_version = 3.11
files = fastlit
follow_imports = skip
ignore_missing_imports = True
warn_unused_configs = True

[mypy-fastlit.ui.text]
ignore_errors = True

[mypy-fastlit.ui.dataframe]
ignore_errors = True

[mypy-fastlit.ui.widgets]
ignore_errors = True

[mypy-fastlit.ui.layout]
ignore_errors = True
